apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configmap
data:
  quarkus.datasource.username: pm4
  quarkus.datasource.jdbc.url: jdbc:postgresql://postgresql-service:5432/pm4?ApplicationName=PM4 Hallo
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  quarkus.datasource.password: YWlzdXJmZ2gzNDk4N3Ro