apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloquarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloquarkus
  template:
    metadata:
      labels:
        app: helloquarkus
    spec:
      containers:
      - name: helloquarkus
        image: ghcr.io/rschumm/pm4quarkus/helloquarkus:latest
        ports:
        - containerPort: 8080
        env:
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: quarkus.datasource.username
        - name: QUARKUS_DATASOURCE_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: quarkus.datasource.jdbc.url
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: quarkus.datasource.password
        - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
          value: update
        - name: QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT
          value: import.sql

---
apiVersion: v1
kind: Service
metadata:
  name: helloquarkus-service
spec:
  selector:
    app: helloquarkus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proposals-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: scmy.pm4.init-lab.ch
      http:
        paths:
          - backend:
              service:
                name: helloquarkus-service
                port:
                  number: 80
            path: /proposal
            pathType: Prefix
