name: CI for Quarkus Proposals App 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'temurin' 

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run tests with Maven
      run: mvn test

    - name: Generate test reports
      run: mvn surefire-report:report

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports/*.xml