name: CI for Quarkus Proposals App 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin' 
     
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: docker-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          docker-${{ github.ref }}-

    - name: Run tests with Maven
      run: mvn test


