name: CI for Quarkus Proposals App 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: PM4 Checkout code
      uses: actions/checkout@v4

    - name: PM4 Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin' 
        cache: 'maven'

    - name: PM4 Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: PM4 Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /var/lib/docker
        key: docker-cache-${{ runner.os }}-${{ github.ref }}
        restore-keys: |
          docker-cache-${{ runner.os }}-

    - name: PM4 Enable Testcontainers Reuse
      run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

    - name: PM4 Run tests with Maven
      run: mvn package

    - name: PM4 Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: target/

    - name: PM4 Upload Dockerfiles
      uses: actions/upload-artifact@v4
      with:
        name: dockerfiles
        path: src/main/docker/

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Download Dockerfiles
      uses: actions/download-artifact@v4
      with:
        name: dockerfiles

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/${{ github.repository }}/helloquarkus:latest .
        docker push ghcr.io/${{ github.repository }}/helloquarkus:latest



