name: CI for Quarkus Proposals App 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: PM4 Checkout code
      uses: actions/checkout@v4

    - name: PM4 Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin' 
        cache: 'maven'

    - name: PM4 Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: PM4 Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /var/lib/docker
        key: docker-cache-${{ runner.os }}-${{ github.ref }}
        restore-keys: |
          docker-cache-${{ runner.os }}-

    - name: PM4 Enable Testcontainers Reuse
      run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

    - name: PM4 Run tests with Maven
      run: mvn test


